### ISSUE TITLE
Item/Block Tags are not functioning properly

### ISSUE THREAD

**Issue by WenXin20** [minecraftabnormals/Upgrade-Aquatic#54]
`Minecraft v1.14.4`
`Forge v28.1.106`
`Upgrade Aquatic v1.4.2`

This seems to affect several tags, including the block tag for stairs, item tags for walls and conduits, etc.
I discovered the following text in the log:
[Full Log](https://gist.github.com/WenXin20/f156b05e11426420b2561e17c5b6a126)
Log Excerpt: 
```
[19:10:53] [Server-Worker-16/ERROR]: Couldn't read item tag list minecraft:flower_pots from minecraft:tags/items/flower_pots.json in data pack Default
com.google.gson.JsonParseException: Unknown value 'upgrade_aquatic:potted_pickerelweed_blue'
	at net.minecraft.tags.Tag$Builder.lambda$fromJson$0(Tag.java:156) ~[?:?]
	at net.minecraft.tags.Tag$Builder$$Lambda$10983/2140815313.get(Unknown Source) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_51]
	at net.minecraft.tags.Tag$Builder.func_219783_a(Tag.java:155) ~[?:?]
	at net.minecraft.tags.TagCollection.lambda$reload$3(TagCollection.java:101) [?:?]
	at net.minecraft.tags.TagCollection$$Lambda$10971/478651462.get(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
```

**Comment by SmellyModder** [comment]
Working on a fix now

**Comment by SmellyModder** [comment]
Should be fixed in next version

**Comment by WenXin20** [comment]
I've noticed that there are still broken tags.
For the stairs block & item tags, there is the number 3 at the top of the file in front of the curly bracket. 
For the flower_pots item tag, the log says it contains unknown values, probably because potted flowers don't exist as an item.
The same for the supports_conduit item tag, the logs says that `upgrade_aquatic:prismarine_coral_wall_fan` is an unknown value.
